### PR TITLE
Updated default recipes to new syntax

### PR DESCRIPTION
**Pull request by Gabo6480**
Updated the default recipes to the new syntax.

### CODE REVIEW

**Comment by Gabo6480** [comment]
Pull this before the enchantment recipes

**Comment by jacky8399** [comment]
I'm not sure about the `\t` change, as YAML specifically disallows using tabs to indent blocks.

**Comment by Gabo6480** [comment]
That's why the \t are replaced with "   ", so in the case that the user accidentally writes a \t the plugin will still load the recipe

**Comment by jacky8399** [comment]
The point is that indentation is important to YAML parsing, and tabs may cause ambiguity in YAML parsing.
Consider the following use case:
```yaml
a:
  b:
\tc: Tab
```
If `\t` characters were replaced with 2 spaces, the parsed output would be `a: {b: null, c: "Tab"}`, whereas if `\t` characters were replaced with 3 spaces, the parsed output would become `a: {b: {c: "Tab"}}`.

And there is no way to know which one the user actually wants, since different editors may display `\t` characters differently.

**Comment by Gabo6480** [comment]
Hmmm, I see, maybe add a Config like, unsafe-yaml-tab-parsing and replace-tab-with, and add a warning above it.

**Comment by jacky8399** [comment]
I don't think this fix is worth the trouble and confusion. Tabs have always been disallowed in YAML files and the way the plugin reads YAML files should be consistent with other plugins. Besides, most modern text editors replace tabs with spaces nowadays so I don't think this is a grave concern.

**Comment by Gabo6480** [comment]
Alright man, it's your mod, feel free to rollback that change when merging.
I added it because the text editor in the mc server interface that I use
does not change \t for spaces automatically. And since I'm used to using
tab when indenting, I was getting frustrated when the error popped up.

**Comment by jacky8399** [comment]
Merged in 895f820, thanks!

As for indenting with tabs, YAML actually supports indenting with a single space, so you can replace all your tab keystrokes with spaces and I think it would work just fine.

**Pull request closed without merging**
